# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: TestAWSServiceConnection
  displayName: 'Test AWS Service Connection'
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - checkout: self

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'AWSConnection'
      regionName: 'us-east-1'
      awsCommand: 'aws'
      awsSubCommand: 's3 ls'
    displayName: 'Test AWS Connection'
