trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: AWSServiceConnection
    displayName: "Validate AWS Service Connection"
    jobs:
      - job: ValidateServiceConnectionAWS
        displayName: "Run Test Service Connection"
        steps:
          - template: Pipeline-Templates/validate-service-connection.yml

  - stage: SecurityChecks
    displayName: "Security Checks"
    jobs:
      - job: RunCheckov
        displayName: "Run Checkov"
        steps:
          - template: Pipeline-Templates/checkov-analysis.yml

  - stage: PlanGeneration
    displayName: "Generación de Plan"
    jobs:
      - job: GenerateTerraformPlan
        displayName: "Generate Terraform Plan"
        steps:
          - template: Pipeline-Templates/terraform-plan.yml

  - stage: ManualApproval
    displayName: "Aprobación Manual"
    jobs:
      - job: ManualApprovalJob
        displayName: "Manual Approval Job"
        steps:
          - template: Pipeline-Templates/manual-approval.yml

  - stage: DeployPlan
    displayName: "Despliegue del Plan"
    jobs:
      - job: DeployTerraformPlan
        displayName: "Deploy Terraform Plan"
        steps:
          - template: Pipeline-Templates/terraform-deploy.yml
